# Generated by Django 5.0.3 on 2024-03-31 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityhubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintlike',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintcomment',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='complaintlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='evencomment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='evencomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='eventlike',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventlike',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='cityhubapp.userinterest'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event', 'Εκδήλωση'), ('complaint', 'Παράπονο')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityhubapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityhubapp.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintComment',
        ),
        migrations.DeleteModel(
            name='ComplaintLike',
        ),
        migrations.DeleteModel(
            name='EvenComment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventLike',
        ),
    ]
